### ISSUE TITLE
"TypeError: 'list' object is not callable" when running multiworker.py

### ISSUE THREAD

**Issue by ksamuel** [meebo/pistil#3]
After pip installing pistil and gunicorn in a virtualenv, I tried to run the example multiworker.py and got:

```
2011-08-12 10:46:49 [4574] [INFO] Starting pistil.arbiter 0.1.0
2011-08-12 10:46:49 [4574] [INFO] Using worker: [(<class '__main__.MyWorker'>, 30, 'worker', {}, 'w1'), (<class '__main__.MyWorker2'>, 30, 'worker', {}, 'w2'), (<class '__main__.MyWorker2'>, 30, 'kill', {}, 'w3')]
Traceback (most recent call last):
  File "test.py", line 30, in <module>
    arbiter.run()
  File "/home/kevin/.virtualenvs/test/lib/python2.7/site-packages/pistil/arbiter.py", line 237, in run
    self.manage_workers()
  File "/home/kevin/.virtualenvs/test/lib/python2.7/site-packages/pistil/arbiter.py", line 526, in manage_workers
    self.spawn_workers()
  File "/home/kevin/.virtualenvs/test/lib/python2.7/site-packages/pistil/arbiter.py", line 584, in spawn_workers
    self.spawn_worker()
  File "/home/kevin/.virtualenvs/test/lib/python2.7/site-packages/pistil/arbiter.py", line 545, in spawn_worker
    self.timeout/2.0, self.conf, self.worker_args)
TypeError: 'list' object is not callable
```

I'm in ubuntu 11.04 64 bits with pistil 0.1.0 and guniorn 0.12.2

**Comment by ksamuel** [comment]
Installing pistil directly from this repo solved the problem:

pip install git+git://github.com/meebo/pistil.git -U

**Comment by benoitc** [comment]
fixed. 0.2 is now available. Thanks!
