### ISSUE TITLE
gevent worker using an inexistent log facility

### ISSUE THREAD

**Issue by perone** [meebo/pistil#8]
The gevent worker uses a log facility at line 61 (self.log) that doesn't exists.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pistil/arbiter.py", line 490, in spawn_child
    child.init_process()
  File "/usr/local/lib/python2.7/dist-packages/pistil/tcp/gevent_worker.py", line 84, in init_process
    super(TcpGeventWorker, self).init_process()
  File "/usr/local/lib/python2.7/dist-packages/pistil/worker.py", line 114, in init_process
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/pistil/tcp/gevent_worker.py", line 61, in run
    self.log.info("Parent changed, shutting down: %s", self)
AttributeError: 'MyWorker' object has no attribute 'log'
```

**Comment by perone** [comment]
Fixed at 78002af682f71e7340a6cf3aef59fa1b6cfb80a9.
